version: "2"
run:
  timeout: 5m

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - ireturn
    - mnd
    - nestif
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 30
    lll:
      line-length: 180
    gocognit:
      min-complexity: 60
    gosec:
      excludes:
        - G115

  exclusions:
    generated: lax
    warn-unused: true
    paths:
      - '_test\.go'
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
