package rtsp

import "errors"

var (
	ErrNotStarted            = errors.New("rtsp: demuxer is not started")
	ErrNoSupportedTrack      = errors.New("rtsp: no supported audio/video track in SDP")
	ErrNoSupportedVideoTrack = ErrNoSupportedTrack
	ErrUnexpectedStatusLine  = errors.New("rtsp: malformed status line")
	ErrUnexpectedInterleaved = errors.New("rtsp: unexpected interleaved frame")

	errUnsupportedURLScheme             = errors.New("rtsp: unsupported URL scheme")
	errOptionsFailed                    = errors.New("rtsp: OPTIONS failed")
	errDescribeFailed                   = errors.New("rtsp: DESCRIBE failed")
	errSetupFailed                      = errors.New("rtsp: SETUP failed")
	errPlayFailed                       = errors.New("rtsp: PLAY failed")
	errPauseFailed                      = errors.New("rtsp: PAUSE failed")
	errAuthenticationFailed             = errors.New("rtsp: authentication failed")
	errKeepAliveSetParameterFailed      = errors.New("rtsp: SET_PARAMETER keepalive failed")
	errKeepAliveOptionsFailed           = errors.New("rtsp: OPTIONS keepalive failed")
	errUnsupportedAudioCodecType        = errors.New("rtsp: unsupported audio codec type")
	errUnsupportedCodecType             = errors.New("rtsp: unsupported codec type")
	errMissingAACDepacketizer           = errors.New("rtsp: missing AAC depacketizer")
	errEmptyInterleavedFrame            = errors.New("rtsp: empty interleaved frame")
	errInvalidAACSizelength             = errors.New("rtsp: invalid AAC sizelength")
	errInvalidAACIndexlength            = errors.New("rtsp: invalid AAC indexlength")
	errInvalidAACIndexdeltalength       = errors.New("rtsp: invalid AAC indexdeltalength")
	errAACPayloadTooShort               = errors.New("rtsp: AAC payload too short")
	errAACAUHeadersTruncated            = errors.New("rtsp: AAC AU headers truncated")
	errAACAUIndexBitsExceedHeaderLength = errors.New("rtsp: AAC AU index bits exceed header length")
	errAACAUPayloadTruncated            = errors.New("rtsp: AAC AU payload truncated")
	errBitReaderOverflow                = errors.New("rtsp: bit reader overflow")
	errH264PayloadTooShort              = errors.New("h264: payload is too short")
	errH264InvalidFUAPacket             = errors.New("h264: invalid FU-A packet")
	errH264NonStartingFUAPacket         = errors.New("h264: non-starting FU-A packet")
	errH264PacketLossWhileDecodingFUA   = errors.New("h264: packet loss while decoding FU-A")
	errH264AccessUnitTooBig             = errors.New("h264: access unit too big")
	errH264InvalidSTAPAPacket           = errors.New("h264: invalid STAP-A packet")
	errH264InvalidSTAPAPayloadSize      = errors.New("h264: invalid STAP-A payload size")
	errH264TooManyNALUsInAccessUnit     = errors.New("h264: too many NALUs in access unit")
	errRTCPPacketTooShort               = errors.New("rtsp: RTCP packet too short")
	errUnsupportedRTCPVersion           = errors.New("rtsp: unsupported RTCP version")
	errInvalidRTCPPacketLength          = errors.New("rtsp: invalid RTCP packet length")
	errRTCPSenderReportTooShort         = errors.New("rtsp: RTCP sender report too short")
)

var errNeedMorePackets = errors.New("rtsp: need more packets")
